### ISSUE TITLE
Cannot remove duplicate tag

### ISSUE THREAD

**Issue by halemiles** [traggo/server#70]
**Describe the bug**
I have created a duplicate tag by mistake and now I cannot remove it. I am being warned with the following message "Delete Tag: tag 'elements' is used in dashboard 'Work' entry 'Main Projects', remove this reference before deleting the tag"

**To Reproduce**
1. Create a tag "test"
2. Use "test" tag in at least one time sheet entry
3. Create another tag called "test"
4. Attempt to remove either of the "test" tags and receive warning.

**Expected behavior**
I think you should be able to remove one of the tags. 

**Screenshots**
None

**Additional context**
- 0.1.1@3b3c478e
- Docker compose file
- Nginx reverse proxy

**Comment by jmattheis** [comment]
Uhh, it shouldn't be possible to create duplicate tags. The validation was faulty and allowed to create a tag with different casing, but keys will be normalized to lowercase which resulted in exactly the same tag.

Which database do you use?

**Comment by halemiles** [comment]
I'm using this docker compose file so it should use whatever database is default. I think in my case I'm using sqlite3.
```
version: "3.0"
services:
  traggo:
    image: traggo/server:latest
    ports:
      - 3030:3030
    environment:
      TRAGGO_DEFAULT_USER_NAME: "admin"
      TRAGGO_DEFAULT_USER_PASS: "password"
    volumes:
      - ./traggodata:/opt/traggo/data
```
